monitor.alsa.rules = [
  {
    matches = [
      {
        device.name = "alsa_card.usb-RayBit_RayBit_3_4_11_50V20240429010-02"
      }
    ]
    actions = {
      update-props = {
        api.alsa.soft-mixer = true
      }
    }
  }
]
